-- Create table
CREATE TABLE public.signatories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  show_name boolean NOT NULL DEFAULT false,
  first_name text NOT NULL,
  last_name text NOT NULL,
  affiliation text NOT NULL,
  gender text,
  career_stage text,
  country_of_origin text,
  age integer,
  email text NOT NULL,
  country_of_residence text,
  orcid text,
  comment text,
  pledge_1_1_1 boolean NOT NULL DEFAULT true,
  pledge_1_1_2 boolean NOT NULL DEFAULT true,
  pledge_1_1_3 boolean NOT NULL DEFAULT true,
  pledge_1_1_4 boolean NOT NULL DEFAULT true,
  pledge_1_1_5 boolean NOT NULL DEFAULT true,
  pledge_1_1_6 boolean NOT NULL DEFAULT true,
  pledge_1_1_7 boolean NOT NULL DEFAULT true,
  pledge_1_1_8 boolean NOT NULL DEFAULT true,
  pledge_1_1_9 boolean NOT NULL DEFAULT true,
  pledge_1_2_1 boolean NOT NULL DEFAULT true,
  pledge_1_2_2 boolean NOT NULL DEFAULT true,
  pledge_1_2_3 boolean NOT NULL DEFAULT true,
  pledge_1_2_4 boolean NOT NULL DEFAULT true,
  pledge_1_3_1 boolean NOT NULL DEFAULT true,
  pledge_1_3_2 boolean NOT NULL DEFAULT true,
  pledge_1_3_3 boolean NOT NULL DEFAULT true,
  pledge_1_3_4 boolean NOT NULL DEFAULT true,
  pledge_1_3_5 boolean NOT NULL DEFAULT true,
  pledge_1_3_6 boolean NOT NULL DEFAULT true,
  pledge_1_3_7 boolean NOT NULL DEFAULT true,
  pledge_1_3_8 boolean NOT NULL DEFAULT true,
  pledge_1_3_9 boolean NOT NULL DEFAULT true,
  pledge_1_4_1 boolean NOT NULL DEFAULT true,
  pledge_1_4_2 boolean NOT NULL DEFAULT true,
  pledge_1_4_3 boolean NOT NULL DEFAULT true,
  pledge_1_4_4 boolean NOT NULL DEFAULT true,
  pledge_1_4_5 boolean NOT NULL DEFAULT true,
  pledge_1_4_6 boolean NOT NULL DEFAULT true,
  pledge_1_5_1 boolean NOT NULL DEFAULT true,
  pledge_1_5_2 boolean NOT NULL DEFAULT true,
  pledge_1_5_3 boolean NOT NULL DEFAULT true,
  pledge_1_5_4 boolean NOT NULL DEFAULT true,
  pledge_2_1_1 boolean NOT NULL DEFAULT true,
  pledge_2_1_2 boolean NOT NULL DEFAULT true,
  pledge_2_1_3 boolean NOT NULL DEFAULT true,
  pledge_2_1_4 boolean NOT NULL DEFAULT true,
  pledge_2_1_5 boolean NOT NULL DEFAULT true,
  pledge_2_1_6 boolean NOT NULL DEFAULT true,
  pledge_2_2_1 boolean NOT NULL DEFAULT true,
  pledge_2_2_2 boolean NOT NULL DEFAULT true,
  pledge_2_2_3 boolean NOT NULL DEFAULT true,
  pledge_2_2_4 boolean NOT NULL DEFAULT true,
  pledge_2_2_5 boolean NOT NULL DEFAULT true,
  pledge_2_2_6 boolean NOT NULL DEFAULT true,
  pledge_2_2_7 boolean NOT NULL DEFAULT true,
  pledge_2_2_8 boolean NOT NULL DEFAULT true,
  pledge_2_3_1 boolean NOT NULL DEFAULT true,
  pledge_2_3_2 boolean NOT NULL DEFAULT true,
  pledge_2_3_3 boolean NOT NULL DEFAULT true,
  pledge_3_1_1 boolean NOT NULL DEFAULT true,
  pledge_3_1_2 boolean NOT NULL DEFAULT true,
  pledge_3_1_3 boolean NOT NULL DEFAULT true,
  pledge_3_1_4 boolean NOT NULL DEFAULT true,
  pledge_3_1_5 boolean NOT NULL DEFAULT true,
  pledge_3_1_6 boolean NOT NULL DEFAULT true,
  pledge_3_1_7 boolean NOT NULL DEFAULT true,
  pledge_3_1_8 boolean NOT NULL DEFAULT true,
  pledge_3_1_9 boolean NOT NULL DEFAULT true,
  pledge_3_1_10 boolean NOT NULL DEFAULT true,
  pledge_3_2_1 boolean NOT NULL DEFAULT true,
  pledge_3_2_2 boolean NOT NULL DEFAULT true,
  pledge_3_2_3 boolean NOT NULL DEFAULT true,
  pledge_3_2_4 boolean NOT NULL DEFAULT true,
  pledge_3_2_5 boolean NOT NULL DEFAULT true,
  pledge_3_2_6 boolean NOT NULL DEFAULT true,
  pledge_3_2_7 boolean NOT NULL DEFAULT true,
  pledge_3_2_8 boolean NOT NULL DEFAULT true,
  pledge_3_2_9 boolean NOT NULL DEFAULT true,
  pledge_3_2_10 boolean NOT NULL DEFAULT true,
  pledge_3_2_11 boolean NOT NULL DEFAULT true,
  pledge_3_3_1 boolean NOT NULL DEFAULT true,
  pledge_3_3_2 boolean NOT NULL DEFAULT true,
  pledge_3_3_3 boolean NOT NULL DEFAULT true,
  pledge_3_3_4 boolean NOT NULL DEFAULT true,
  pledge_3_4_1 boolean NOT NULL DEFAULT true,
  pledge_3_4_2 boolean NOT NULL DEFAULT true,
  pledge_3_4_3 boolean NOT NULL DEFAULT true,
  pledge_3_4_4 boolean NOT NULL DEFAULT true,
  pledge_3_4_5 boolean NOT NULL DEFAULT true,
  pledge_3_4_6 boolean NOT NULL DEFAULT true,
  pledge_3_5_1 boolean NOT NULL DEFAULT true,
  pledge_3_5_2 boolean NOT NULL DEFAULT true,
  pledge_3_5_3 boolean NOT NULL DEFAULT true,
  pledge_3_5_4 boolean NOT NULL DEFAULT true,
  pledge_3_5_5 boolean NOT NULL DEFAULT true,
  pledge_3_5_6 boolean NOT NULL DEFAULT true,
  pledge_3_6_1 boolean NOT NULL DEFAULT true,
  pledge_3_6_2 boolean NOT NULL DEFAULT true,
  pledge_3_6_3 boolean NOT NULL DEFAULT true,
  pledge_3_6_4 boolean NOT NULL DEFAULT true,
  pledge_3_6_5 boolean NOT NULL DEFAULT true,
  CONSTRAINT signatories_pkey PRIMARY KEY (id)
);

-- Enable RLS for table
ALTER TABLE public.signatories ENABLE ROW LEVEL SECURITY;

-- Define policy for RLS
CREATE POLICY "Allow anonymous inserts"
ON public.signatories FOR INSERT TO anon
WITH CHECK (true);