site_name: EEG100 Manifesto
nav:
  - Manifesto: index.md
  - signatories.md
  - contributors.md
  - glossary.md
  - references.md
not_in_nav: |
  introduction.md
  validity.md
  democratization.md
  responsibility.md
  conclusion.md
theme:
  name: material
  icon:
    logo: fontawesome/solid/brain
  palette:
    primary: blue grey
    accent: blue
  font:
    text: Roboto Flex
  features:
  - navigation.sections
  - navigation.instant
  - navigation.top
  custom_dir: overrides
plugins:
  - include-markdown
  - autorefs
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.blocks.html
  - pymdownx.blocks.details
  - pymdownx.blocks.admonition
  - pymdownx.tasklist:
      clickable_checkbox: true
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - toc:
      toc_depth: 3


extra_css:
  - stylesheets/extra.css
  - stylesheets/form.css
  - stylesheets/snackbar.css
  - stylesheets/floating_buttons.css

extra_javascript:
  - "https://unpkg.com/@supabase/supabase-js@2"
  - javascript/extra_javascript.js