site_name: EEG100 Manifesto Draft
nav:
  - index.md
  - signatories.md
  - contributors.md
  - glossary.md
  - references.md
not_in_nav: |
  intentions.md
  validity.md
  democratization.md
  responsibility.md
  conclusion.md
theme:
  name: material
  icon:
    logo: fontawesome/solid/brain
  palette:
    primary: blue grey
    accent: blue
  font:
    text: Roboto Flex
  features:
  - navigation.sections
  - navigation.instant
  custom_dir: overrides
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - attr_list
  - def_list


extra_css:
  - stylesheets/extra.css